### ISSUE TITLE
Camera not working

### ISSUE THREAD

**Issue by TyposBro** [aj-naik/Emotion-Music-Recommendation#63]
I tried running the project on my PC but camera isn't working.

I tried upgrading with **pip-upgrade** and installing **pandastable**  but still camera doesn't work

Env:
PC: Manjaro (Linux 5.15.72-1)
Browser: Brave (Version 1.44.112 Chromium: 106.0.5249.119 (64-bit))
Python 3.9.12
Flask 2.2.2

**Comment by aj-naik** [comment]
Must be a version issue. Try downloading to versions available June 2021 it might work then
